base_model:
  _target_: base_model.Llama3Instruct8B


base_model_name: llama3i8b
  
# reference_params_results:
#   - 'saved_models/llama3i8b/gsm8k/learnable_params.pt'
#   - 'saved_models/llama3i8b/mbpp/learnable_params.pt'
#   - 'saved_models/llama3i8b/ai2arc/learnable_params.pt'

reference_params_results:
  - "/home/liukaiyuan/project/self-adaptive-llms/results/ckpy/gsm8k_policy_params_best_test_acc_0.7725549658832449.pt"
  - "/home/liukaiyuan/project/self-adaptive-llms/results/ckpy/mbpp_policy_params_best_test_acc_0.6868686868686869.pt"
  - "/home/liukaiyuan/project/self-adaptive-llms/results/ckpy/arc_policy_params_best_test_acc_0.8960437710437711.pt"